version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orbit
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.local
    depends_on:
      - postgres
      - mongo

volumes:
  pgdata:
  mongodata: